# Project Information
site_name: Philippines vACC Knowledge Base
site_url: https://learn.vatphil.com
site_author: Jacob Allen, Juan Carlos. Inspired by Kenzo Tayko, Emilio Perez, Michael Uy
edit_uri: edit/main/docs/
copyright: Copyright Â© 2026 Philippines vACC. All rights reserved. The information contained on this website is for flight simulation purposes only.

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized
  - mike
  - glightbox
  

# Configuration
theme:
  name: material
  font:
    text: Mulish

  palette:
    - scheme: vatphil
      primary: 
      accent: amber


  logo: assets/img/vatphil-wlogo.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking    
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.footnote.tooltips
    - content.tooltips
    - content.tabs.link
  favicon: assets/img/favicon.ico

extra_css:
  - stylesheets/vatphil.css

extra:
  analytics:
    provider: google
    property: G-779QHKRL0K
  social:
    - icon: fontawesome/brands/facebook 
      link: https://facebook.com/philippinesvacc
      name: Facebook Page
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/vatphil
      name: Instagram
    - icon: material/home
      link: https://vatphil.com
      name: Philippines vACC Main Website

  version:
    provider: mike


markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - tables
  - abbr
  - pymdownx.snippets
